# Q1. What are data structures, and why are they important?

- Ans - Data  structure is a way of organizing and storing data so that they can be access and munipulate easly.
  - Various data structure are:-
    - List
    - String
    - Tuples
    - Dictionary
    - Array
- importance of data structure:-
  - we can easily modify
  - we can easily use the data in future
  - Memory managmet

# Q2. Explain the difference between mutable and immutable data types with examples?

# Mutable Data types -
  - Modification - Mutable data types are those which once created cant be modified in the future.
  - Ex - Stringa and tuple are immutable data types.
  - Performance - Faster for modification.
  - Memory address - Remain same when value is assigned.
# Immutable Data types
  - Modification - immutable data types are thos which once created can be modified.
  - Ex - List, Distionarty, Set are mutable data types.
  - Performance - Slower for modification, faster to access.
  - Memory address - Chaenges when any new value is assigned.

In [ ]:
#immutable
# string
name = "asad"
name[0] = "b" # it will give error -> str object not supported

TypeError: 'str' object does not support item assignment

In [ ]:
#Mutable
#List
name = ["asad", "rohan", "anil"]
name.insert(1, "pradum") # pradum will e added to index 1 and all the items present at index 1 and after that will be shifted 1 index right.
name

['asad', 'pradum', 'rohan', 'anil']

# Q3. What are the main differences between lists and tuples in Python?

# List
  - Mutablity-  List are mutable data type.
  - Syntax - List can be defined using squaare bracket "[]"
  - Performance - Lists are slower due to its dynamic size and mutablity.
  - Memory - List consume more memory due to its flexiblity.
  - Use case - suitable for items that can be changed.
  - Methods - List have more builtin function. eg- append, insert, etc.  
  - homogenity - Lists are homogeneous i.e. it can contain any data string, int, float, complex, etc.


#Tuples
  - Mutablity - Tuples are immutable data types.
  - Syntax - Tuples can be defined using parenthesis "()"
  - Performance - Tuples are Faster due to its static size and immutablity.
  - Memory - Tuples consumes less memory due to its immutablity.
  - Use case - suitable for items that can't be changed.
  - Methods - Tuples have less builtin function. eg - count, index
  - homogenity - Tuples are hetrogeneous

In [ ]:
#List
fruits = ["banana", "apple", "papaya"]
fruits.insert(3, "mango")
fruits

['banana', 'apple', 'papaya', 'mango']

In [ ]:
#Tuples
tuple1 = ("asad", "rishav", "pradum")
tuple1[0]

'asad'

# Q4. Describe how dictionaries store data.

- Dictionary is a data type that store's data in key value pair.
- Keys are unique and immutable
- {"keys" : "

In [ ]:
competition_winner = {"Math Competition": "Ajay", "Science Competition": "Rohan", "English Competition": "AAruhi", "Gk Competition":("Sanjay", "Alaudin", "Rishi") }
competition_winner

{'Math Competition': 'Ajay',
 'Science Competition': 'Rohan',
 'English Competition': 'AAruhi',
 'Gk Competition': ('Sanjay', 'Alaudin', 'Rishi')}

In [ ]:
competition_winner["English Competition"]

'AAruhi'

# Q5. Why might you use a set instead of a list in Python?

  - one might use set insted of list in case :-
  1. duplicate data - in case when you dont want to include duplicate data in your collection whereas list allows duplicate data.
  - eg. List - name= ["Ajay", "rohan", "sanjay", "sunjay"]
    - set - name = ("Ajay", "rohan", "sanjay")
  2. Membership data - Provide faster membership testing making it much more efficient for operation like checking duplicates or searching for something whereas list is sower compared to set, each element is checked sequenctially.
  3. Set-Operation - set support mathematical operation like union, intersection,etc. whereas list does not support set-operation.
  4. performance - set is generally faster for operation like adding or removing the element due to underlying hash table whereas in list adding or removing require shifting the elements.

# Q6. What is a string in Python, and how is it different from a list?

Ans - String are set of charecter where charecter are single unit of text which is helpful to represent and manipulate textual data.
  - Strings contain letter, number,punctuation marks and even spaces.
  - Strings once created cant be changed meaning its immutable.
  - String is homogeneous data type.
   - eg - "He is a good boy"

- Where as lists are orderd collection of items.
- List contain element of any data type.
- Lists are mutable data type which means once it's created it can be modified.
- List is hetrogeneous data type.
  - eg - ["asad", "rohan", "sunil"]

In [ ]:
#String
a = "hi i am a good boy"
type(a)

str

In [ ]:
a[0] = "b"  #error ->  str object not supported

TypeError: 'str' object does not support item assignment

In [ ]:
#List
name = ["ayush", "aryman", "sunil"]
name[0]

'ayush'

# Q7. How do tuples ensure data integrity in Python?

  - Tuples maintain's its integretity by being immutable means once it's created it doesn't allow any moddification.
  - Since it is immutable it doesn't allow users to change the data, this ensure data remain constant throughout the program.
  -Tuples guarantee fixed collection of data that should not change throught the program. This consistency is important where data is integrithy is important.

In [ ]:
student_id = (2403126, 2106356, 2212365)
type(student_id)

tuple

In [ ]:
student_id[0] = 2406126 # it will give error, because tuple is immutble

TypeError: 'tuple' object does not support item assignment

# Q8. What is a hash table, and how does it relate to dictionaries in Python?

  - A hash table is a data structure that provides a way to efficiently store and retrieve data using a key-value pair model. It works by using a hash function to map keys to specific indices in an underlying array or list, which allows for fast access, insertion, and deletion operations.
  - Dictionary also use key value pair to store its data. each time we insert or access a pair, pyhon uses a hash function to map the key to its location.
  - {key: value}

In [ ]:
competition_winner = {"Math Competition": "Ajay", "Science Competition": "Rohan", "English Competition": "AAruhi", "Gk Competition":("Sanjay", "Alaudin", "Rishi") }
competition_winner

{'Math Competition': 'Ajay',
 'Science Competition': 'Rohan',
 'English Competition': 'AAruhi',
 'Gk Competition': ('Sanjay', 'Alaudin', 'Rishi')}

In [ ]:
competition_winner.pop("Gk Competition") # removing the values from the dictionary

('Sanjay', 'Alaudin', 'Rishi')

# Q9. Can lists contain different data types in Python?

yes, list contain different data types in python, list is hetrogeneous it can contain diffrent data types like int, string, bool, etc., at the same time

In [ ]:
data = ["rohan", 62, 5.6, 32, "Banglore", 6 + 5j, True]
data

['rohan', 62, 5.6, 32, 'Banglore', (6+5j), True]

- Yes, List list are hetrogeneous  it can contain diffrent data types like "string", "int", "boolean", "complex", etc.

In [ ]:
#List
list1 = ["asad", 1, 2.2, True, 2 + 5j ]
list1

['asad', 1, 2.2, True, (2+5j)]

# Q10. Explain why strings are immutable in Python?

- String are immutable means once its created it can't be changed.
- The immutability of Python string is very useful as it helps in hashing, performance optimization, safety, ease of use, etc.

In [ ]:
a = "Hi this is me."
a[3] = "f"   # error

TypeError: 'str' object does not support item assignment

# Q11. What advantages do dictionaries offer over lists for certain tasks?

  - Advantages of dictionaries over list:-
    - Dictionaries are optimized for fast lookups using a key, whereas  lists require a linear search.
    - Dictionaries store data as key-value pairs, which is ideal for situations where you want to associate a value with a unique identifier (key), whereas Lists, on the other hand, store elements sequentially without any explicit association between elements.
    - Dictionaries automatically prevent duplicate keys wheras Lists allow duplicate values, which could lead to confusion if you need to store unique elements.
    - Dictionaries allow access to values via any hashable type as a key wheras Lists only allow access via index.

# Q12. Describe a scenario where using a tuple would be preferable over a list?

  - in case where we do not require our data to be manipulated means if we have data of addhar no so we dont want to do any manipulation with that data or suppose we have student id so in these case we don't want our data to be manipulated.

In [ ]:
student_id = (240710, 240711, 240712, 240713)
student_id

(240710, 240711, 240712, 240713)

In [ ]:
student_id[0] = 26536 # we cant do cahnge's  in the tuple

TypeError: 'tuple' object does not support item assignment

# Q13. How do sets handle duplicate values in Python?

- In Python, sets automatically handle duplicate values by removing them. A set is a collection of unique elements, which means that it only stores one occurrence of each value, automatically discarding duplicates.
- When you try to add a duplicate element to a set, Python will simply ignore it.
- If you create a set from a list or any iterable containing duplicate values, Python will automatically remove the duplicates during the conversion process.

In [ ]:
my_set = {1, 2, 3}
my_set.add(2)
print(my_set)

{1, 2, 3}

# Q14. How does the “in” keyword work differently for lists and dictionaries?

- list - When the in keyword is used with a list, it checks if the specified element exists within the list. It searches through the list and returns True if the element is found, and False if it is not.
- dictionary - When the in keyword is used with a dictionary, it checks if the specified key exists in the dictionary, not the value. By default, it looks for the key in the dictionary's keys.

In [ ]:
# list
name = ["ajay", "rohan", "sunil", "vijay"]
"ajay" in name

True

In [ ]:
# dictionary
my_dict = {"a": 1, "b": 2, "c": 3}
print("a" in my_dict)
print("d" in my_dict)

True
False

# Q15. Can you modify the elements of a tuple? Explain why or why not?

  - No, we can't modify the elements of tuple because tuples are immutable, which means onces tuple is created we can't modify its content.

In [ ]:
t = ("pwskills", 1, 6, 60.6, True, 5 + 6j)
t

('pwskills', 1, 6, 60.6, True, (5+6j))

In [ ]:
t[0] = "apple" # we will get error

TypeError: 'tuple' object does not support item assignment

# Q16. What is a nested dictionary, and give an example of its use case?

- Nested dictionary is  a kind of dictionaries where one dictionary is a parent Dictionary and inside it one or more then one child dictionries are present or in other words dictionry inside dictionry.
- {key:{name: bac, age: 26, address:{ashbcasyd}}}

In [ ]:
empl_detail = {"emp001": {"name": "Rohan", "Age": 26, "Skills":{"Language": "Python", "expertires": "Data Analytics"} }, "emp0002":{"name": "Ajay" , "Age": 29, "Skills":{"Language": "Java script", "Experties": "Web dev."}}}
empl_detail

{'emp001': {'name': 'Rohan',
  'Age': 26,
  'Skills': {'Language': 'Python', 'expertires': 'Data Analytics'}},
 'emp0002': {'name': 'Ajay',
  'Age': 29,
  'Skills': {'Language': 'Java script', 'Experties': 'Web dev.'}}}

# Q17. Describe the time complexity of accessing elements in a dictionary?

- Average time complexity:
- The time complexity of accessing elements in a dictionary in Python is O(1) on average. This means that, in most cases, retrieving the value associated with a specific key is done in constant time, regardless of the size of the dictionary.
- Worst-Case Time Complexity:
- In the worst case, dictionary access could be O(n) if there are hash collisions that are handled poorly. A hash collision occurs when two keys have the same hash value, and the dictionary needs to handle this collision by chaining or probing. However, modern Python implementations minimize this risk by using techniques like open addressing and resizeable hash tables, making hash collisions rare.

- Thus, in practice, O(1) is the expected time complexity for most dictionary operations, including accessing elements, inserting new items, and deleting items.

# Q18. In what situations are lists preferred over dictionaries?

- List are prefered over dictionries in cases:-
  - Where collection of list is simple in that case we can use list.
  - where key value pair is not important we can use list.
  - where order of the list is important we can use list.
  - when you need to acces the element by index not by keys in that case we can use list.
  - When the data in in sequence or in range we can use list.

# Q19. Why are dictionaries considered unordered, and how does that affect data retrieval?

- List are important over dictionary in cases:-
  - Key value pair is not important, we can use list in that case.
  - in list we can maintain the oder of the elements wheras in dictionary order is not important.
  - list allow to access the index of the element, whereas in dictionary we have to access the key and if there is more the one value then we have to specify the index also which makes it complex.
  - list are used where data is simple a collection of value wheras dictionary is little complex storing key and values.
  - Adding or removing element in list is very easy, wheras in dictionay its complex.

# Q20. Explain the difference between a list and a dictionary in terms of data retrieval.


- List
    - Ordered collection of elements indexed by integers.
    - Access by index (e.g., my_list[0]).
    - O(1) for accessing by index.
    - Preserves the order of insertion.
    - Data is accessed by position (index).
    - Best for ordered collections.
- Dictionary
    - Unordered collection of key-value pairs.
    - Access by key (e.g., my_dict['key']).
    - O(1) average for retrieving by key.
    - Insertion order is preserved (Python 3.7+), but not guaranteed in earlier versions.
    - Data is accessed by a unique key.
    - Best for fast lookups and key-value associations.

# Practicle Questions

# Q1. Write a code to create a string with your name and print it?

In [ ]:
name = "asad"
print(name)

asad

# Q2. Write a code to find the length of the string "Hello World"?

In [ ]:
name = "Hello World"
print(len(name))

11

# Q3. Write a code to slice the first 3 characters from the string "Python Programming"?

In [ ]:
name = "Python Programming"
name[0:3] # it will statrt from 0 index and ends at index 2.

'Pyt'

# Q4. Write a code to convert the string "hello" to uppercase?

In [ ]:
name = "hello"
name.upper()

'HELLO'

# Q5. Write a code to replace the word "apple" with "orange" in the string "I like apple"?

In [ ]:
fruit = "I like apple"
fruit.replace("apple", "orange")

'I like orange'

# Q6. Write a code to create a list with numbers 1 to 5 and print it?

In [ ]:
number = []
for i in range(1, 6):
  number.append(i)
print(number)
type(number)

[1, 2, 3, 4, 5]

list

# Q7. Write a code to append the number 10 to the list [1, 2, 3, 4]?

In [ ]:
number = [1, 2, 3, 4]
number.append( 10)
number

[1, 2, 3, 4, 10]

# Q8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]?

In [ ]:
number = [1, 2, 3, 4, 5]
number.remove(3)
number

[1, 2, 4, 5]

# Q9. Write a code to access the second element in the list ['a', 'b', 'c', 'd'].

In [ ]:
number = ['a', 'b', 'c', 'd']
number[1]

'b'

# Q10. Write a code to reverse the list [10, 20, 30, 40, 50].

In [ ]:
reverse = [10, 20, 30, 40, 50]
reverse[::-1]

[50, 40, 30, 20, 10]

# Q11. Write a code to create a tuple with the elements 10, 20, 30 and print it.

In [ ]:
tup = (10, 20, 30)
print(tup)
type(tup)

(10, 20, 30)

tuple

# Q12. Write a code to access the first element of the tuple ('apple', 'banana', 'cherry').

In [ ]:
tup = ('apple', 'banana', 'cherry')
tup[0]

'apple'

# Q13. Write a code to count how many times the number 2 appears in the tuple (1, 2, 3, 2, 4, 2).

In [ ]:
tup = (1, 2, 3, 2, 4, 2)
tup.count(2)

3

# Q14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

In [ ]:
animal = ('dog', 'cat', 'rabbit')
animal.index("cat")

1

# Q15. Write a code to check if the element "banana" is in the tuple ('apple', 'orange', 'banana').

In [ ]:
fruits = ('apple', 'orange', 'banana')
if ("banana" in fruits):
  print("Banana is present in fruit")
else:
  print("Banana is not present in fruit")

Banana is present in fruit

# Q16. Write a code to create a set with the elements 1, 2, 3, 4, 5 and print it.

In [ ]:
Set1 = {1, 2, 3, 4, 5}
print(Set1)

{1, 2, 3, 4, 5}

# Q17. Write a code to add the element 6 to the set {1, 2, 3, 4}.

In [ ]:
set1 = {1, 2, 3, 4}
set1.add(6)
set1

{1, 2, 3, 4, 6}

# Q18. Write a code to create a tuple with the elements 10, 20, 30 and print it.

In [ ]:
# Same as Q11.
tup = (10, 20, 30)
print(tup)
type(tup)

(10, 20, 30)

tuple

# Q19. Write a code to access the first element of the tuple ('apple', 'banana', 'cherry').

In [ ]:
# Same as Q12.
tup = ('apple', 'banana', 'cherry')
tup[0]

'apple'

# Q20. Write a code to count how many times the number 2 appears in the tuple (1, 2, 3, 2, 4, 2).

In [ ]:
# Same as Q13.
tup = (1, 2, 3, 2, 4, 2)
tup.count(2)

3

# Q21. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

In [ ]:
# Same as Q14.
animal = ('dog', 'cat', 'rabbit')
animal.index("cat")

1

# Q22. Write a code to check if the element "banana" is in the tuple ('apple', 'orange', 'banana').

In [ ]:
# Same as Q15.
fruits = ('apple', 'orange', 'banana')
if ("banana" in fruits):
  print("Banana is present in fruit")
else:
  print("Banana is not present in fruit")

Banana is present in fruit

# Q23. Write a code to create a set with the elements 1, 2, 3, 4, 5 and print it.

In [ ]:
# Same as Q16.
Set1 = {1, 2, 3, 4, 5}
print(Set1)

{1, 2, 3, 4, 5}

# Q24. Write a code to add the element 6 to the set {1, 2, 3, 4}.

In [ ]:
# Same as Q17.
set1 = {1, 2, 3, 4}
set1.add(6)
set1

{1, 2, 3, 4, 6}